### ISSUE TITLE
Incorrect accept header in example

### ISSUE THREAD

**Issue by sharafian** [interledger/paymentpointers.org#8]
<img width="751" alt="Screen Shot 2020-10-19 at 12 03 35 PM" src="https://user-images.githubusercontent.com/3362563/96500048-1fa45f80-1203-11eb-821c-6832a5959781.png">

The accept header in this example is `application/json` but as an SPSP request it should be `application/spsp4+json`

**Comment by adrianhopebailie** [comment]
That example is an Open Payments meta-data request: https://docs.openpayments.dev/discovery#metadata
